Updated microide directory declaration.

diff --git a/templates/microide_install.template b/templates/microide_install.template
--- a/templates/microide_install.template
+++ b/templates/microide_install.template
@@ -116,7 +116,6 @@ installEclipse() {
     else 
         echo 'Installing Eclipse ---------------------------------------------------------------' >> log.log
         mkdir -p eclipse-installer
-#        sudo apt-get install default-jre
         tar --extract --file=$DOWNLOAD_DIR/$ECLIPSE_FILENAME
         #redirect eclipse installer product index
         cd eclipse-installer
@@ -128,6 +127,9 @@ installEclipse() {
         rm eclipse-installer/setups/microIDE/microide.product.setup.windows
         rm -r microIDE-$BRANCH_NAME
         rm -r $DOWNLOAD_DIR/$BRANCH_NAME.zip
+	# set path to microide
+	echo $MICROIDE_DIR
+	sed -i -e 's,value="${installation.location|uri}",value="'"$MICROIDE_DIR"'",g' "eclipse-installer/setups/microIDE/microide.product.setup"
     fi
 }
 
@@ -179,46 +181,46 @@ checkArchitecture() {
 }
 
 instal() {
-checkArchitecture
-echo 'Installing required packages:'
-installARMToolchain 'addAptToGetPackagesToInstall'
-installOpenOCD 'addAptToGetPackagesToInstall'
-installEclipse 'addAptToGetPackagesToInstall'
-installClangFormat 'addAptToGetPackagesToInstall'
-installCppcheck 'addAptToGetPackagesToInstall'
-installGCC
-echo $APT_GET_PACKAGES_TO_INSTALL
-sudo apt-get update
-sudo apt-get install $APT_GET_PACKAGES_TO_INSTALL
+    checkArchitecture
+    echo 'Installing required packages:'
+    installARMToolchain 'addAptToGetPackagesToInstall'
+    installOpenOCD 'addAptToGetPackagesToInstall'
+    installEclipse 'addAptToGetPackagesToInstall'
+    installClangFormat 'addAptToGetPackagesToInstall'
+    installCppcheck 'addAptToGetPackagesToInstall'
+    installGCC
+    echo $APT_GET_PACKAGES_TO_INSTALL
+    sudo apt-get update
+    sudo apt-get install $APT_GET_PACKAGES_TO_INSTALL
 
-#------------------------------------- toolchains -----------------------------
-echo 'Unpacking toolchain patch and eclipse installer setup configuration.'
-echo 'Unpacking toolchain patch and eclipse installer setup configuration.---------------' >> log.log
-if ! unzip $DOWNLOAD_DIR/$BRANCH_NAME.zip >> log.log; then
-    echo 'Unable to unzip repozitory files'
-    echo 'Aborting...'
-    exit 1
-fi 
-echo 'Installing ARM Toolchain...'
-installARMToolchain
-# ------------------------------------ tools ---------------------------------
-echo 'Installing tools'
-installOpenOCD
-# ---------------------------------- eclipse ---------------------------------
-echo 'Installing Eclipse'
-installEclipse
-#install clang-format
-installClangFormat
+    #------------------------------------- toolchains -----------------------------
+    echo 'Unpacking toolchain patch and eclipse installer setup configuration.'
+    echo 'Unpacking toolchain patch and eclipse installer setup configuration.---------------' >> log.log
+    if ! unzip $DOWNLOAD_DIR/$BRANCH_NAME.zip >> log.log; then
+        echo 'Unable to unzip repozitory files'
+        echo 'Aborting...'
+        exit 1
+    fi 
+    echo 'Installing ARM Toolchain...'
+    installARMToolchain
+    # ------------------------------------ tools ---------------------------------
+    echo 'Installing tools'
+    installOpenOCD
+    # ---------------------------------- eclipse ---------------------------------
+    echo 'Installing Eclipse'
+    installEclipse
+    #install clang-format
+    installClangFormat
 
-#removing not needed files
-rm -r $DOWNLOAD_DIR
+    #removing not needed files
+    rm -r $DOWNLOAD_DIR
 
-echo '-----------------------------------------------------------------------------'
-echo 'Please install eclipse in following directory:'
-echo $MICROIDE_DIR
+    echo '-----------------------------------------------------------------------------'
+    echo 'Please install eclipse in following directory:'
+    echo $MICROIDE_DIR
 
-#starting eclipse installer
-./eclipse-installer/eclipse-inst
+    #starting eclipse installer
+    ./eclipse-installer/eclipse-inst
 }
 
 # script starting point
@@ -230,7 +232,7 @@ if [ "$1" = "--checkDownload" ]; then
 	download
 else
 	echo "Starting normal install."
-	#download
+	download
 	instal
 fi
 
