adding LLVM into windows installer.

diff --git a/templates/microide_install.template b/templates/microide_install.template
--- a/templates/microide_install.template
+++ b/templates/microide_install.template
@@ -171,7 +171,15 @@ installGCC() {
     fi
 }
 
+checkArchitecture() {
+    if [ "$(uname -i)" != "x86_64" ]; then
+        echo "This script can be used only on 64 bit systems. Aborting."
+        exit 1
+    fi
+}
+
 instal() {
+checkArchitecture
 echo 'Installing required packages:'
 installARMToolchain 'addAptToGetPackagesToInstall'
 installOpenOCD 'addAptToGetPackagesToInstall'
@@ -222,7 +230,7 @@ if [ "$1" = "--checkDownload" ]; then
 	download
 else
 	echo "Starting normal install."
-	download
+	#download
 	instal
 fi
 
