Updated linux template file, added cmsis-dap interface into openocd configuration

diff --git a/templates/microide_install.template b/templates/microide_install.template
--- a/templates/microide_install.template
+++ b/templates/microide_install.template
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# This script was tested on ubuntu 16.04 LTS, it may require some changes to run on other versions
+
 # Absolute path to this script, e.g. /home/user/bin/foo.sh
 SCRIPT=$(readlink -f "$0")
 # Absolute path this script is in, thus /home/user/bin
@@ -36,6 +38,8 @@ then
     echo Aborting...
     exit 1
 fi
+echo 'Downloading HIDAPI (OpenOCD component)...'
+wget -O $DOWNLOAD_DIR/hidapi.zip https://github.com/signal11/hidapi/archive/master.zip
 echo 'Downloading Eclipse...'
 wget -O $DOWNLOAD_DIR/$ECLIPSE_FILENAME $ECLIPSE_URL
 #md5_local=$(md5sum "$DOWNLOAD_DIR/$ECLIPSE_FILENAME" | awk '{print $1}')
@@ -49,6 +53,43 @@ wget -O $DOWNLOAD_DIR/$ECLIPSE_FILENAME $ECLIPSE_URL
 #fi
 }
 
+
+installOpenOCD() {
+    echo 'Installing HIDAPI ----------------------------------------------------------------' >> $MICROIDE_DIR/log.log
+    sudo apt-get install autoconf libudev-dev libusb-1.0-0-dev libtool pkg-config    
+    mkdir -p tmp
+    if ! unzip $DOWNLOAD_DIR/hidapi.zip -d tmp >> $MICROIDE_DIR/log.log; then
+        echo 'Unable to install HIDAPI, aborting -----------------------------------------------' >> $MICROIDE_DIR/log.log
+        echo 'Unable to unzip repozitory files'
+        echo 'Aborting...'
+        exit 1
+    fi 
+    cd tmp/hidapi-master
+    ./bootstrap >> $MICROIDE_DIR/log.log
+    ./configure >> $MICROIDE_DIR/log.log
+    echo 'Compilling HIDAPI ----------------------------------------------------------------' >> $MICROIDE_DIR/log.log
+    make -j 4 >> $MICROIDE_DIR/log.log
+    echo 'Installing (make install) HIDAPI -------------------------------------------------' >> $MICROIDE_DIR/log.log
+    sudo make install 
+    sudo ldconfig
+    cd ../../
+    
+    echo 'Installing openOCD'    
+    mkdir -p tools/openocd
+    echo 'Extracting OpenOCD... ------------------------------------------------------------' >> $MICROIDE_DIR/log.log
+    tar --extract --file=$DOWNLOAD_DIR/$OPENOCD_FILENAME -C tmp >> $MICROIDE_DIR/log.log
+    echo 'Compilling OpenOCD'
+    echo 'Compilling OpenOCD ---------------------------------------------------------------' >> $MICROIDE_DIR/log.log
+    cd tmp/${OPENOCD_FILENAME%.tar.gz}
+    ./configure --enable-stlink --enable-ti-icdi --enable-ulink --enable-cmsis-dap --enable-jlink --enable-oocd_trace --prefix=$MICROIDE_DIR/$OPENOCD_LOCATION >> $MICROIDE_DIR/log.log
+    make -j 4 >> $MICROIDE_DIR/log.log
+    echo 'Installing OpenOCD ---------------------------------------------------------------' >> $MICROIDE_DIR/log.log
+    make install
+    sudo cp contrib/60-openocd.rules /etc/udev/rules.d/
+    sudo usermod -aG plugdev $USER
+    cd ../../
+    rm -r tmp
+}
 
 instal() {
 #------------------------------------- toolchains -----------------------------
@@ -73,21 +114,7 @@ cp -r microIDE-$BRANCH_NAME/toolchains/gcc-arm-none-eabi-patch/${ARM_GCC_TOOLCHA
 
 # ------------------------------------ tools ---------------------------------
 echo 'Installing tools'
-echo 'Installing openOCD'
-sudo apt-get install libusb-1.0-0-dev libtool pkg-config
-mkdir -p tools/openocd
-echo 'Extracting OpenOCD...'
-mkdir -p tmp
-tar --extract --file=$DOWNLOAD_DIR/$OPENOCD_FILENAME -C tmp
-echo 'Compilling OpenOCD'
-echo 'Compilling OpenOCD ---------------------------------------------------------------' >> log.log
-cd tmp/${OPENOCD_FILENAME%.tar.gz}
-./configure --enable-stlink --enable-jlink --enable-oocd_trace --enable-buspirate --prefix=$MICROIDE_DIR/$OPENOCD_LOCATION >> log.log
-make  >> log.log
-make install
-sudo cp contrib/60-openocd.rules /etc/udev/rules.d/
-sudo usermod -aG plugdev $USER
-cd ../../
+installOpenOCD
 # ---------------------------------- eclipse ---------------------------------
 echo 'Installing Eclipse'
 echo 'Installing Eclipse ---------------------------------------------------------------' >> log.log
@@ -103,7 +130,6 @@ cp -r microIDE-$BRANCH_NAME/eclipse-installer/setups/* eclipse-installer/setups
 mv eclipse-installer/setups/microIDE/microide.product.setup.linux eclipse-installer/setups/microIDE/microide.product.setup
 rm eclipse-installer/setups/microIDE/microide.product.setup.windows
 rm -r microIDE-$BRANCH_NAME
-rm -r tmp
 rm -r $DOWNLOAD_DIR/$BRANCH_NAME.zip
 #install clang-format
 sudo apt-get install clang-format
